// Environment variables for Firebase configuration
// This file is generated by the server to inject secure environment variables

// Make environment variables available globally
window.VITE_FIREBASE_API_KEY = "${VITE_FIREBASE_API_KEY}";
window.VITE_FIREBASE_PROJECT_ID = "${VITE_FIREBASE_PROJECT_ID}";
window.VITE_FIREBASE_APP_ID = "${VITE_FIREBASE_APP_ID}";

console.log('Environment variables loaded');